class ConstantValues {
  ConstantValues._();
  static final List<String> motorcycleList = [
    'Honda',
    'Yamaha',
    'Suzuki',
    'Kawasaki',
    'Harley-Davidson',
    'Ducati',
    'BMW Motorrad',
    'KTM',
    'Triumph',
    'Aprilia',
    'Moto Guzzi',
    'Royal Enfield',
    'Indian Motorcycle',
    'Husqvarna Motorcycles',
    'MV Agusta'
  ];

  static final List<String> nigerianBanks = [
    'Access Bank',
    'Zenith Bank',
    'First Bank of Nigeria',
    'United Bank for Africa (UBA)',
    'Guaranty Trust Bank (GTBank)',
    'Stanbic IBTC Bank',
    'Union Bank of Nigeria',
    'Fidelity Bank',
    'Ecobank Nigeria',
    'Sterling Bank',
    'Wema Bank',
    'Polaris Bank',
    'FCMB (First City Monument Bank)',
    'Heritage Bank',
    'Unity Bank',
    'Keystone Bank',
    'Jaiz Bank',
    'SunTrust Bank Nigeria',
    'Providus Bank',
    'Titan Trust Bank',
    'Globus Bank'
  ];
  static final List<String> motorcycleModelList = [
    'Honda CBR600RR',
    'Yamaha YZF-R1',
    'Suzuki GSX-R750',
    'Kawasaki Ninja ZX-6R',
    'Harley-Davidson Sportster',
    'Ducati Panigale V4',
    'BMW S1000RR',
    'KTM 1290 Super Duke R',
    'Triumph Street Triple',
    'Aprilia RSV4',
    'Moto Guzzi V7',
    'Royal Enfield Classic 500',
    'Indian Scout',
    'Husqvarna Vitpilen 701',
    'MV Agusta Brutale 800'
  ];

  static final List<String> motorcycleColorList = [
    'Red',
    'Blue',
    'Black',
    'White',
    'Green',
    'Yellow',
    'Orange',
    'Silver',
    'Gray',
    'Purple',
    'Brown',
    'Gold',
    'Maroon',
    'Cyan',
    'Pink'
  ];

  static final genderList = [
    "Male",
    "Female",
  ];

  static final List<String> vehicleList = [
    'Toyota',
    'Volkswagen',
    'Ford',
    'Honda',
    'Chevrolet',
    'Nissan',
    'BMW',
    'Mercedes-Benz',
    'Hyundai',
    'Kia',
    'Audi',
    'Subaru',
    'Mazda',
    'Lexus',
    'Jaguar',
    'Porsche',
    'Ferrari',
    'Lamborghini',
    'Volvo',
    'Land Rover',
    'Jeep',
    'Dodge',
    'Chrysler',
    'Buick',
    'Cadillac',
    'Acura',
    'Infiniti',
    'Mitsubishi',
    'Tesla',
    'Mini',
    'Maserati',
    'Alfa Romeo',
    'Bentley',
    'Rolls-Royce',
    'Bugatti',
    'Aston Martin',
    'Peugeot',
    'Renault',
    'Citroën',
    'Skoda',
    'SEAT',
    'Fiat',
    'Suzuki',
    'Isuzu',
    'Saab',
    'Lincoln',
    'Genesis',
    'McLaren',
    'Pagani',
    'Koenigsegg'
  ];
}
