name: bglory_rides
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  go_router: ^14.1.4
  contained_tab_bar_view: ^0.8.0
  intl_phone_field: ^3.2.0
  otp_text_field_v2: ^1.0.3
  animated_rating_stars: ^1.0.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_riverpod: ^2.5.1

  # Product Specific
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  gap: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.2
  scroll_date_picker: ^3.8.0
  google_maps_flutter: ^2.6.1
  back_button_interceptor: ^7.0.3
  
  json_annotation: ^4.9.0




  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logo/
    - assets/onboarding_images/
    - assets/animation/
    - assets/images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo/ICONWHITE.png'